site_name: DietPi.com Docs
site_url: https://dietpi.com/docs/
site_description: 'Official documentation pages for DietPi OS'
site_author: 'DietPi.com Team'
copyright: 'Copyright © 2020 DietPi.com | Documentation Distributed under <a target="_blank"
            href="http://creativecommons.org/licenses/by-sa/4.0/">CC-BY-4.0</a>'

repo_name: DietPi-Docs
repo_url: https://github.com/MichaIng/DietPi-Docs
docs_dir: docs

theme:
  name: 'material'
  custom_dir: docs/overrides
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
   - tabs
  #logo: 'assets/images/logo.png'
  favicon: https://dietpi.com/favicon.ico
    
markdown_extensions:  
  - attr_list
  - admonition
  - codehilite
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - extra
  - pymdownx.magiclink

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MichaIng/DietPi
    - icon: fontawesome/solid/home
      link: https://dietpi.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DietPi_
      
extra_css:
   - "css/custom.css"

nav:
  - 'HOME' : 
      - 'Overview' : index.md
      - 'Installation' : 'user-guide_install.md'
      - 'Getting started' : 'user-guide_overview.md'
      - 'Optimised software list' : 'user-optimised-software.md'
      - 'Supported SBC' : 'hardware-supported_sbc.md'
      - 'Community Tutorials' : 'https://dietpi.com/phpbb/viewforum.php?f=15'
      - 'Advanced configuration & DietPi Tools' : 'user-guide_tools.md'
      - 'Troubleshooting' : 'https://dietpi.com/phpbb/viewforum.php?f=11'
      - 'Release notes' : 'release-notes-updates.md'
      - 'Request features' : 'https://feathub.com/MichaIng/DietPi'
      - 'Report issues' : 'https://github.com/MichaIng/DietPi/issues'
  - 'OPTIMISED SOFTWARE' :
      - 'Desktops & Utilities' : 'dietpi-software-desktop.md'
      - 'Media Systems': 'dietpi-software-media.md'
      - 'Remote Desktop Access' : 'dietpi-software-remote-desktop.md'
      - 'Cloud & Backups' : 'dietpi-software-cloud.md'
      - 'BitTorrent / Download Tools' : 'dietpi-software-bittorrent.md'
      - 'Gaming / Emulation' : 'dietpi-software-gaming.md'
      - 'Camera / Surveillance' : 'dietpi-software-camera.md'
  - 'COMMUNITY' : 
      - 'DietPi Forums & Community' : 'https://dietpi.com/phpbb/viewforum.php?f=5'
