site_name: DietPi Documentation
repo_url: https://github.com/MichaIng/DietPi-Docs
site_author: "DietPi Team"

theme:
  name: 'material'
  # logo: 'assets/images/logo.png'
  favicon: https://dietpi.com/favicon.ico

markdown_extensions:  
  - attr_list
  - admonition
  - codehilite
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/solid/home
      link: https://dietpi.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DietPi_

extra_css:
   - "css/custom.css"

# Copyright
copyright: '&copy; 2020, DietPi'

nav:
  - 'Overview' : index.md
  - 'Installation' : 'user-guide_install.md'
  - 'Getting started': 
      - 'Overview' : 'user-guide_overview.md'
      - 'DietPi Tools' : 'user-guide_tools.md'
  - 'Optimised software' : 'user-optimised-software.md'
  - 'Supported SBCs' : 'hardware-supported_sbc.md'
  - 'Updates' : 'release-notes-updates.md'
  - 'Community' : 'https://dietpi.com/phpbb/index.php'
  - 'Request features' : 'https://github.com/MichaIng/DietPi/issues/new/choose'
  - 'Report issues' : 'https://github.com/MichaIng/DietPi/issues/new?template=bug_report.md'
