name: Markdown tests
on: push
jobs:
  Check_Markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # .markdownlintrc: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "*.md **/*.md"
  Check_Spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # .spellcheck.yaml: https://github.com/marketplace/actions/github-spellcheck-action#spellcheck-configuration-file
      # .wordlist.txt
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.5.0
  Check_BuildAndLinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install Python dependencies
        run: |
          python3 -m pip install -U pip
          pip3 install -r requirements.txt
      - name: Build MkDocs
        run: mkdocs build
      - name: Link Checker
        uses: peter-evans/link-checker@v1
        with:
          args: -r README.md site
